
server:
  port: 9090

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:xe
    username: system
    password: password
#    url: jdbc:oracle:thin:@carsnownew_medium?TNS_ADMIN=/home/ta40463/Documents/sampleminiproj/backend/Wallet_carsNowDB
#    username: admin
#    password: CarsNow.com2021




  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


security:
  oauth2:
    resource:

      token-info-uri: http://localhost:9090/oauth/check_token
#      id: mobile
    client:
      client-id: mobile
      client-secret: pin
      user-authorization-uri: http://localhost:9090/oauth/authoriza
      access-token-uri: http://localhost:9090/oauth/token



logging:
  io:
    swagger:
      models:
        parameters:
          AbstractSerializableParameter: error
